<x-admin-layout>
    <div class="content">

        {{-- Breadcrumb --}}
        <x-admin.breadcrumb title="Permission List" route="permission.create">
            <x-permission name="can-create-permission">
                <x-admin.button button_id="add_permission" button_name="Add Permission"/>
            </x-permission>
        </x-admin.breadcrumb>

        {{-- Permissions Table --}}
        <x-admin.card-table
            title="Roles & Permissions List"
            :headers="['#', 'Permission Name', 'Guard Name', 'Group Name', 'Status', 'Action']"
        >
            @forelse ($permissions as $index => $permission)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $permission->name ?? '-' }}</td>
                    <td>{{ $permission->guard_name ?? '-' }}</td>
                    <td>{{ $permission->group_name ?? '-' }}</td>
                    <td>
                        @if($permission->is_active)
                            <span class="badge bg-success">Active</span>
                        @else
                            <span class="badge bg-danger">Inactive</span>
                        @endif
                    </td>
                    <td>
                        <div class="action-icon d-inline-flex">

                            <x-permission name="can-edit-permission">
                                <a href="#" class="me-2 edit"
                                   data-bs-toggle="modal"
                                   data-bs-target="#update_permission"
                                   data-id="{{ $permission->id }}"
                                   data-name="{{ $permission->name }}"
                                   data-group_name="{{ $permission->group_name }}"
                                   data-guard_name="{{ $permission->guard_name }}"
                                   data-is_active="{{ $permission->is_active }}">
                                    <i class="ti ti-edit"></i>
                                </a>
                            </x-permission>

                            <x-permission name="can-delete-permission">
                                <x-admin.delete :id="$permission->id" target="permissions.destroy" msg="You want to delete the permission, this can't be undone once you delete." />
                            </x-permission>
                        </div>

                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="text-center py-3">No roles or permissions found.</td>
                </tr>
            @endforelse
        </x-admin.card-table>

    </div>

    @include('pages.permission.modal.add-permission-modal')
    @include('pages.permission.modal.update-permission-modal')

    @push('scripts')
        <script>
            $(document).ready(function () {
                // Shared logic for Group Select change (Add Modal)
                $('#group_select').on('change', function () {
                    let value = $(this).val();
                    if (value === '__new__') {
                        $('#group_input').removeClass('d-none').val('').focus();
                        $('#group_name').val('');
                    } else {
                        $('#group_input').addClass('d-none');
                        $('#group_name').val(value);
                    }
                });

                $('#group_input').on('input', function () {
                    $('#group_name').val($(this).val());
                });

                // Shared logic for Edit Group Select change (Update Modal)
                $(document).on('change', '#edit_group_select', function () {
                    let value = $(this).val();
                    if (value === '__new__') {
                        $('#edit_group_input').removeClass('d-none').val('').focus();
                        $('#edit_group_name').val('');
                    } else {
                        $('#edit_group_input').addClass('d-none');
                        $('#edit_group_name').val(value);
                    }
                });

                $(document).on('input', '#edit_group_input', function () {
                    $('#edit_group_name').val($(this).val());
                });

                // Click Edit button
                $(document).on('click', '.edit', function () {
                    let id = $(this).data('id');
                    let name = $(this).data('name');
                    let groupName = $(this).data('group_name');
                    let isActive = $(this).data('is_active');

                    $('#edit_permission').val(id); // edit_{model} id generated by form-modal
                    $('#edit_name').val(name);
                    $('#edit_is_active').val(isActive);

                    // Check if group exists in dropdown
                    if ($("#edit_group_select option[value='" + groupName + "']").length) {
                        $('#edit_group_select').val(groupName).trigger('change');
                    } else {
                        // If group doesn't exist → show input
                        $('#edit_group_select').val('__new__').trigger('change');
                        $('#edit_group_input').val(groupName);
                        $('#edit_group_name').val(groupName);
                    }
                });
            });
        </script>
    @endpush
</x-admin-layout>
